import type { CollectionFixture, MetaobjectDefinitionFixture, MetaobjectFixture, ProductFixture } from "../domain/types.js";

export type PresetName = "minimal" | "fashion" | "electronics";

function seededRandom(seed: number) {
  let state = seed >>> 0;
  return () => {
    state = (state * 1664525 + 1013904223) >>> 0;
    return state / 0x100000000;
  };
}

function slugify(input: string): string {
  return input.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

const presets = {
  minimal: { adjectives: ["Classic", "Simple", "Everyday"], nouns: ["Mug", "Tote", "Notebook"], type: "Demo" },
  fashion: { adjectives: ["Studio", "Essential", "Modern", "Relaxed"], nouns: ["Tee", "Jacket", "Hoodie", "Cap"], type: "Apparel" },
  electronics: { adjectives: ["Compact", "Wireless", "Smart", "Portable"], nouns: ["Speaker", "Charger", "Keyboard", "Headphones"], type: "Electronics" }
} satisfies Record<PresetName, {adjectives: string[]; nouns: string[]; type: string}>;

export function generateFixtures(options: {seed: number; products: number; collections: number; preset: PresetName}) {
  const random = seededRandom(options.seed);
  const preset = presets[options.preset];
  const products: ProductFixture[] = Array.from({length: options.products}, (_, i) => {
    const adjective = preset.adjectives[Math.floor(random() * preset.adjectives.length)]!;
    const noun = preset.nouns[Math.floor(random() * preset.nouns.length)]!;
    const title = `${adjective} ${noun} ${i + 1}`;
    const handle = slugify(title);
    const sizes = options.preset === "fashion" ? ["S", "M", "L"] : ["Default"];
    return {
      key: handle,
      handle,
      title,
      descriptionHtml: `<p>Generated by RXR Shopify Fixtures using seed ${options.seed}.</p>`,
      vendor: "RXR Fixtures",
      productType: preset.type,
      status: "ACTIVE",
      tags: ["fixture", options.preset],
      options: [{name: options.preset === "fashion" ? "Size" : "Title", values: sizes}],
      variants: sizes.map((size, variantIndex) => ({
        sku: `RXR-${options.seed}-${i + 1}-${variantIndex + 1}`,
        price: (20 + Math.floor(random() * 180) + .99).toFixed(2),
        options: {[options.preset === "fashion" ? "Size" : "Title"]: size}
      })),
      metafields: [{namespace: "rxr_fixtures", key: "fixture_seed", type: "number_integer", value: String(options.seed)}]
    };
  });
  const collections: CollectionFixture[] = Array.from({length: options.collections}, (_, i) => ({
    key: `${options.preset}-collection-${i + 1}`,
    handle: `${options.preset}-collection-${i + 1}`,
    title: `${options.preset[0]!.toUpperCase()}${options.preset.slice(1)} Collection ${i + 1}`,
    descriptionHtml: "<p>Generated fixture collection.</p>"
  }));
  const definitions: MetaobjectDefinitionFixture[] = [{
    type: "rxr_fixture_note",
    name: "RXR Fixture Note",
    displayNameKey: "title",
    fields: [
      {key: "title", name: "Title", type: "single_line_text_field", required: true},
      {key: "body", name: "Body", type: "multi_line_text_field"}
    ]
  }];
  const metaobjects: MetaobjectFixture[] = [{
    type: "rxr_fixture_note",
    handle: `seed-${options.seed}`,
    fields: {title: `Fixture seed ${options.seed}`, body: `Preset: ${options.preset}`}
  }];
  return {products, collections, definitions, metaobjects};
}
